// Todas las cadenas visibles del Tablero de Operaciones, en un solo lugar.
// El tablero es sólo en español (pantalla de la oficina). Si algún día se
// quiere bilingüe, esto se convierte en un diccionario por idioma.
export const T = {
  // Encabezado
  boardTitle: 'Tablero de Operaciones de Oficina',
  tz: 'ET',

  // Banda de personal
  onTheClock: 'En turno',
  clockUnavailable: 'Estado de asistencia no disponible',
  nobodyClockedIn: 'Nadie ha marcado entrada ahora',
  atTheShops: 'En los talleres',
  dragHint: 'Arrástralo a un trabajo para asignarlo',
  statusWorking: 'Trabajando',
  statusLunch: 'Almuerzo',
  statusMaterial: 'Compra de material',
  statusWaiting: 'En espera',
  statusOnClock: 'En turno',
  lunchParen: ' (almuerzo)',

  // Columnas
  colAwaiting: 'Esperando PO / Por Programar',
  colScheduled: 'Trabajos Programados',
  colAppointments: 'Citas Importantes',
  emptyAwaiting: 'No hay trabajos esperando una PO.',
  emptyScheduled: 'No hay trabajos programados.',
  emptyAppointments: 'No hay citas importantes.',
  cantConnect: 'Sin conexión. Reintentando…',
  page: 'Página',
  shown: 'en pantalla',

  // Banner de conexión
  staleOnline: (t) => `Sin conexión con el servidor — mostrando la última actualización de las ${t}.`,
  staleOffline: (t) => `Sin conexión — mostrando la última actualización de las ${t}. Reconectando…`,
  earlier: 'antes',

  // Pie
  lastUpdated: 'Última actualización',
  online: 'En línea',
  offline: 'Sin conexión — reconectando',
  fullscreen: 'Pantalla completa',
  exitFullscreen: 'Salir de pantalla completa',
  editMode: 'Modo Edición',
  exitEditMode: 'Salir de Modo Edición',
  restNow: 'Reposo',
  exitToApp: 'Volver a la app',

  // Pantalla de reposo (protector de pantalla)
  idleHint: 'Toca la pantalla para ver el tablero',

  // Tarjetas de trabajo
  clientTBD: 'Cliente por definir',
  est: 'Est.',
  onHold: 'En Pausa',
  received: 'Recibido',
  day: 'día',
  days: 'días',
  waiting: 'esperando',
  next: 'Siguiente',
  crew: 'Cuadrilla',
  crewEmpty: '— arrastra un nombre aquí',
  dropToAssign: 'Suelta para asignar',
  wasDue: 'Vencía',
  scheduled: 'Programado',
  start: 'Inicio',
  doneBy: 'Termina',
  delayed: 'Retrasado',
  today: 'Hoy',
  poMissing: '⚠ FALTA LA PO — no iniciar el trabajo sin una PO',
  removeFrom: (name, job) => `Quitar a ${name} de ${job}`,

  // Insignias — PO
  po: {
    none: 'Sin PO',
    requested: 'PO Solicitada',
    received: 'PO Recibida',
    approved: 'PO Aprobada',
  },
  // Insignias — prioridad
  priority: {
    urgent: 'Urgente',
    high: 'Alta',
    normal: 'Normal',
    low: 'Baja',
  },
  // Insignias — programación
  schedule: {
    unscheduled: 'Sin Programar',
    tentative: 'Tentativo',
    confirmed: 'Confirmado',
    in_progress: 'En Progreso',
    completed: 'Completado',
  },
  // Insignias — estado de la cita
  confirm: {
    tentative: 'Tentativo',
    confirmed: 'Confirmado',
    completed: 'Completada',
    canceled: 'Cancelada',
  },
  // Insignias — importancia
  importance: {
    critical: 'Crítica',
    important: 'Importante',
  },

  // Línea de tiempo de citas
  tlEmpty: 'No hay citas con hora hoy.',
  tlUpcoming: 'Próximas',
  tlNothingElse: 'Nada más programado.',
  tlCanceled: 'Cancelada',

  // Modo Edición — PIN
  pinTitle: 'Entrar a Modo Edición',
  pinBody: 'Para editar trabajos y citas se necesita el PIN de la oficina. Pídelo a un supervisor si no lo tienes.',
  pinLabel: 'PIN del tablero',
  pinEmpty: 'Ingresa el PIN del tablero.',
  pinWrong: 'PIN incorrecto.',
  cancel: 'Cancelar',
  unlock: 'Desbloquear',

  // Modo Edición — panel
  panelTitle: 'Tablero de Operaciones · Modo Edición',
  panelHint: 'Los cambios aparecen en el tablero en 30 segundos.',
  panelLoadError: 'No se pudieron cargar los registros. Tu sesión de PIN pudo haber terminado — sal y vuelve a entrar a Modo Edición.',
  tabJobs: 'Trabajos',
  tabAppointments: 'Citas',
  searchPlaceholder: 'Buscar por nombre, cliente, N.º de estimado…',
  addJob: '+ Agregar Trabajo',
  addAppointment: '+ Agregar Cita',
  noJobsMatch: 'Ningún trabajo coincide.',
  noApptsMatch: 'Ninguna cita coincide.',
  archived: '(archivado)',
  noClient: 'Sin cliente',
  poShort: 'PO',
  editBtn: 'Editar',

  // Formulario de trabajo
  jfEditTitle: 'Editar Trabajo',
  jfAddTitle: 'Agregar Trabajo',
  jfName: 'Nombre del trabajo *',
  jfClient: 'Cliente / empresa',
  jfNewClientName: 'Nombre del nuevo cliente',
  jfNone: '— ninguno —',
  jfPickExisting: 'Elegir un cliente existente',
  jfNewClient: '+ Nuevo cliente',
  jfLocation: 'Ubicación del trabajo',
  jfEstimate: 'N.º de estimado / trabajo',
  jfPriority: 'Prioridad',
  jfOverallStatus: 'Estado general',
  jfStatusActive: 'Activo',
  jfStatusOnHold: 'En Pausa',
  jfStatusCompleted: 'Completado',
  jfStatusCancelled: 'Cancelado',
  jfPO: 'PO',
  jfPOStatus: 'Estado de PO',
  jfPONone: 'Sin PO',
  jfPORequested: 'Solicitada',
  jfPOReceived: 'Recibida',
  jfPOApproved: 'Aprobada',
  jfPONumber: 'Número de PO',
  jfPOReceivedDate: 'Fecha de recepción de PO',
  jfSchedule: 'Programación',
  jfScheduleStatus: 'Estado de programación',
  jfSchUnscheduled: 'Sin programar',
  jfSchTentative: 'Tentativo',
  jfSchConfirmed: 'Confirmado',
  jfSchInProgress: 'En progreso',
  jfSchCompleted: 'Completado',
  jfSchedDate: 'Fecha programada',
  jfStartTime: 'Hora de inicio',
  jfExpectedCompletion: 'Fecha estimada de término',
  jfCrew: 'Cuadrilla asignada',
  jfNextAction: 'Persona responsable de la siguiente acción',
  jfNotes: 'Notas',
  jfArchive: 'Archivar',
  jfSave: 'Guardar cambios',
  jfAdd: 'Agregar trabajo',
  jfNameRequired: 'El nombre del trabajo es obligatorio.',
  jfConflict: 'Otra persona cambió este trabajo mientras lo editabas.',
  jfLoadLatest: 'Cargar los valores más recientes',
  jfSaveError: 'No se pudo guardar. Inténtalo de nuevo.',
  jfArchiveConfirm: (name) => `¿Archivar «${name}»? Saldrá del tablero pero permanece en los registros.`,
  jfArchiveError: 'No se pudo archivar.',

  // Formulario de cita
  afEditTitle: 'Editar Cita',
  afAddTitle: 'Agregar Cita',
  afTitle: 'Título *',
  afStart: 'Inicio *',
  afEnd: 'Fin',
  afLocation: 'Ubicación o método de reunión',
  afType: 'Tipo',
  afMeetingDefault: 'Reunión (predeterminado)',
  afResponsible: 'Persona responsable',
  afRelatedJob: 'Trabajo relacionado',
  afImportance: 'Importancia',
  afImpNormal: 'Normal',
  afImpImportant: 'Importante',
  afImpCritical: 'Crítica',
  afConfirmation: 'Confirmación',
  afConfTentative: 'Tentativo',
  afConfConfirmed: 'Confirmado',
  afConfCompleted: 'Completada',
  afConfCanceled: 'Cancelada',
  afNotes: 'Notas',
  afCancelAppt: 'Cancelar cita',
  afRemoveBoard: 'Quitar del tablero',
  afClose: 'Cerrar',
  afSave: 'Guardar cambios',
  afAdd: 'Agregar cita',
  afRequired: 'El título y la fecha/hora de inicio son obligatorios.',
  afConflict: 'Otra persona cambió esta cita mientras la editabas.',
  afCancelConfirm: (name) => `¿Marcar «${name}» como cancelada?`,
  afCancelError: 'No se pudo cancelar.',
  afRemoveConfirm: (name) => `¿Quitar «${name}» del tablero? (Permanece en el calendario.)`,
  afRemoveError: 'No se pudo quitar.',
}
